apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certtest.fullname" . }}-db-secret
  labels:
    app: {{ include "certtest.name" . }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }} 