apiVersion: v1
kind: Secret
metadata:
  name: certtest-db-secret
  labels:
    app: certtest
type: Opaque
data:
  password: QXBwbGVAMjAyMA==  # Apple@2020 base64 encoded
stringData:
  # Alternative way to specify the password in plain text
  # password: Apple@2020 